<div class="top-bar">
  <div class="top-bar-left">
    <ul class="dropdown menu" data-dropdown-menu>
      <li class="menu-text"><?=App::config('nazivApp')?></li>
      <li><a href="<?=App::config('url')?>">Početna</a></li>
      <li><a href="<?=App::config('url')?>index/onama">O nama</a></li>
    </ul>
  </div>
  <div class="top-bar-right">
    <ul class="menu">
      <li><a href="<?=App::config('url')?>index/login">Login</a></li>
    </ul>
  </div>
</div>